name: Node.js CI/CD Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GLOBAL_ENV_VAR: "This is a global variable"
jobs:
  build-and-test:
    name: Build and test application
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Run test
        run: npm test
  deploy:
    name: Deploy Application
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://example.com
    steps:
      # Step 1: Check out code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Deploy application
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Deploying application to production..."
          echo "API Key: $API_KEY"
          echo "Database URL: $DATABASE_URL"
          echo "Port: $PORT